### PR TITLE
Multi tag search

### PR DESCRIPTION
**Pull request by annathecrow**
This enables searching for multiple tags at the same time (i.e. "Harry Potter" and "Fluff"), by parsing quoted strings.

This enables the most requested feature (searching for tag combinations) without having to add any GUI. The API technically has one "main tag" and several "other tags", but I checked and the result is same no matter which tag is the main one. 

It does make the form a bit more confusing though.

What do you think?

### CODE REVIEW

**Comment by annathecrow** [comment]
Well,  I accidentally pushed this to live and I have no idea how to roll back, so I'll just merge this, too. If you have any comments, let me know, though!

**Comment by destinationtoast** [comment]
I like the idea!  It doesn't seem to work for me currently...

**Comment by annathecrow** [comment]
Ohhhh, bugger! It *did* work before! Thans for testing it, I'll fix it asap.

**Comment by annathecrow** [comment]
Okay, it works now, fixed by #72. Also, we now have integration tests. Maybe that'll stop me from breaking things when I'm trying to fix other things...

**Comment by destinationtoast** [comment]
Wooo!  Tried it again, and I love it!  :D

**Pull request merged**
